site_name: NGS Analysis Handbook
site_url: https://iliapopov17.github.io/NGS-Handbook/
copyright: Copyright &copy; 2024 Ilia Popov
theme:
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  features:
    - navigation.expand
    - content.code.copy
    - search
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
plugins:
  - search
  
repo_url: https://github.com/iliapopov17/NGS-Handbook
repo_name: iliapopov17/NGS-Handbook

extra:
  social:
    - icon: fontawesome/solid/address-card
      link: https://iliapopov17.github.io/
    - icon: fontawesome/solid/envelope
      link: mailto:<iljapopov17@gmail.com>
    - icon: fontawesome/brands/github 
      link: https://github.com/iliapopov17
    - icon: rsf/RSF_vertical
      link: https://rscf.ru/en/project/25-24-00351/
  analytics:
    provider: google
    property: G-4RBMQR50GK

extra_templates:
  - meta_tags.html